name: 比赛名字1
# 数据目录,含有 子目录,名为 aplusb1,等
data_base_path: demo/contest
# 选手所在的目录
user_base_path: demo/contest/user
problems:
 - name: aplusb1
   time: 1
   memory: 128
   core: 100   #default
   spj: fcmp2   #default
 - name: aplusb2
   time: 1
   memory: 512
   core: 200   #set by self
   # spj: spj.cpp
 - name: aplusb3
   time: 2
   memory: 64
   spj: fcmp2
